---
linters:
  enable-all: true
  disable:
    - gomnd # WARN The linter 'gomnd' is deprecated (since v1.58.0) due to: The linter has been renamed. Replaced by mnd
    - tagliatelle
    - wsl
    - err113
    - nlreturn
    - lll
    - godot
    - varnamelen
    - ireturn
    - exhaustruct
    - execinquery
    - musttag
    - depguard
