---
linters:
  enable-all: true
  disable:
    - tagliatelle
    - wsl
    - err113
    - nlreturn
    - lll
    - godot
    - varnamelen
    - ireturn
    - exhaustruct
    - musttag
    - depguard
    - exportloopref # WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
    - tagalign
