#!/usr/bin/env bash

set -eu

cd "$(dirname "$0")/.."

help=$(ghalint help-all)

echo -n "# Usage

<!-- This is generated by scripts/generate-usage.sh. Don't edit this file directly. -->

$help" > docs/usage.md
